### ISSUE TITLE
Error during projects creation

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-backend#105]
I am trying to create a project with just name and description and an error is returned. This is how the payload looks like:
<img width="689" alt="Screen Shot 2020-04-23 at 16 58 46" src="https://user-images.githubusercontent.com/1638636/80153713-ae516000-8583-11ea-8ef2-44545cae1845.png">

The error returned looks as follows:
<img width="1224" alt="Screen Shot 2020-04-23 at 17 00 40" src="https://user-images.githubusercontent.com/1638636/80153789-d17c0f80-8583-11ea-9a75-fb66f9355679.png">

**Comment by EliuX** [comment]
Is this happening after specifying the JWT?

**Comment by EliuX** [comment]
I came from running it and it worked.
![image](https://user-images.githubusercontent.com/6514740/80227707-a214e380-8613-11ea-8e84-b8aa4a720365.png)
