### ISSUE TITLE
Computed worked time

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-backend#108]
As a user, I want to know the summary of my worked time in the current week.

We need to build an endpoint:

```
GET /time-entries/summary
```

That needs to use the user id from the JWT to query the time entries. We need a response like this:
```
{
   "day": {
      "hours":#
      "minutes":#
      "seconds":#
   },
   "week": {
      "hours":#
      "minutes":#
      "seconds":#
   },
   "month": {
      "hours":#
      "minutes":#
      "seconds":#
   }
}
```

**Comment by EliuX** [comment]
So, more than a week this is going to gather information from now backward in specific periods of time, in this case, days, week, and month.
