### ISSUE TITLE
Make time-entry URI not required

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-backend#111]
We need to make the `uri` field from `time-entry` optional.

**Comment by EliuX** [comment]
After [we discussed this issue](https://ioetec.slack.com/archives/CUD8VFS86/p1588008746022300), we realized that the problem is not that the field `uri` is required, but that it is not nullable. So I will convert all strings fields into nullable ones.

**Comment by enriquezrene** [comment]
same with description @EliuX . I just tried again.
