### ISSUE TITLE
Return all time-entries within a range time

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-backend#122]
As an admin, I want to query all the created time-entries during a specified range of time.

Filters are going to be:
- start-time
- end-time

The endpoint will return:

- email
- project name
- customer name
- start-time
- end-time
- ticker uri
- notes
- technologies
- activity

Data needs to be grouped by user email.

**Comment by fabidick22** [comment]
is this going to return a custom data model? :thinking:
