### ISSUE TITLE
Add a standard utils module

### ISSUE THREAD

**Issue by Angeluz-07** [ioet/time-tracker-backend#147]
After discussing with @fabidick22 we found we need to keep adding functions/abstractions to meet new requirements and keep the code flexible at the same time. 

The idea of custom python modules(files with python code) is working, but the current folder structure of them it seems not to be the best.

We have those custom modules inside namespaces(currently in time-entries and projects). The idea is to set a folder at top level where these custom modules will live in.

This would be the new structure:
```
- tests/
- utils/ <--- the new folder
   worked_time.py <--- custom modules developed on demand
   <module_2>.py
    ...
- time_tracker_api/
...
```
Still in dicussion.

**Comment by enriquezrene** [comment]
Utils are always a bad idea, here is why:
https://www.yegor256.com/2015/02/20/utility-classes-vs-functional-programming.html
https://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html

**Comment by Angeluz-07** [comment]
I get that the main idea is to use classes as much as possible instead of independent functions. I will try to stick to that in favor of flexible code.
