### ISSUE TITLE
Disable automatic clock-outs

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-backend#160]
We implemented a feature to clock out users automatically at midnight. We are facing issues since we are using the time in UTC which is wrong since users are distributed all across the world and for this reason we need to take into account their timezones, for now, let's disable this functionality that will be enabled again after having saved their preferred timezones somewhere.

**Comment by Angeluz-07** [comment]
This is caused by https://github.com/ioet/time-tracker-backend/issues/148
