### ISSUE TITLE
Summary for week incorrect

### ISSUE THREAD

**Issue by astridschneider** [ioet/time-tracker-backend#179]
Today on July 1, the summary for the week reset and started counting from 0. Please fix. 
![Screen Shot 2020-07-01 at 9 53 47 AM](https://user-images.githubusercontent.com/31556785/86262095-0eb4dd00-bb85-11ea-8dff-b6b8fe6a4250.png)

**Comment by Angeluz-07** [comment]
In the discussion to implement #108 . I was  to decided to filter from DB time-entries of the current month and then make the processing by month/week/day. 

The case that is causing this issue was not considered.  The first step would be to change the initial filter of DB.
