### ISSUE TITLE
add database/schema migrations support

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-backend#36]
The API works using a SQL database, we need to add support to DB/schema migrations so we can make evolve the DB structure whenever it is needed.

**Acceptance Criteria**
- DB/schema migrations support is added (https://en.wikipedia.org/wiki/Schema_migration)
- README file should be updated with required instructions to run db migrations up and down
- Current db seeder implementation should be revisited and removed

**Comment by EliuX** [comment]
I will implement this migration system but for Cosmos DB
