### ISSUE TITLE
Https is not working for main page

### ISSUE THREAD

**Issue by EliuX** [ioet/time-tracker-backend#47]
We have problems accessing the main page by HTTPS, but through HTTP everything works correctly. All endpoints are available via HTTPS or HTTP the problem is the main page. The API does not provide logs about this problem.
HTTPS: https://timetracker-api.azurewebsites.net/
HTTP: http://timetracker-api.azurewebsites.net/

**Comment by Angeluz-07** [comment]
I have investigated about this issue and found this thread https://github.com/noirbizarre/flask-restplus/issues/54 . I made a fix #90 with a suggestion of the thread, I tested it by manually running the CI/CD and it worked.
