### ISSUE TITLE
Refactor projects to use Cosmos DB SQL API

### ISSUE THREAD

**Issue by EliuX** [ioet/time-tracker-backend#52]
Right now we have projects working in http://timetracker-api.azurewebsites.net/projects. In Slack, we have been talked about migration from the Azure SQL database serverless to Azure Cosmos DB SQL API. We need to refactor the current database model and API namespace to use the new data access layer. Take into account the [new model](https://www.lucidchart.com/documents/edit/42736c71-b2dd-474b-9cba-dcf7c0559783/uR~JkchVdQXz?beaconFlowId=B8E1D76AAD71623C#?folder_id=home&browser=icon) discussed/reviewed by the team.

**Comment by Angeluz-07** [comment]
Check #57 and #56  for status of ProjectType and Customer Model respectively.
