### ISSUE TITLE
Create Technology Model

### ISSUE THREAD

**Issue by Angeluz-07** [ioet/time-tracker-backend#59]
Create model in `/time_tracker_api` to meet the new design [new design](https://www.lucidchart.com/documents/edit/42736c71-b2dd-474b-9cba-dcf7c0559783/uR~JkchVdQXz?beaconFlowId=B8E1D76AAD71623C) and use new DAL #50 for it.

**Comment by EliuX** [comment]
This is no longer a model in our design
