### ISSUE TITLE
Remove constraints on time-entry creation

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-backend#87]
A time entry needs to be created as soon as the user clicks on a project. In the same way, that it is happening on t-sheets right now. So, we need to remove some required fields during a time-entry creation.

The only fields we have are going to be:
- JWT (injected in headers)
- project_id
- start_date

**Acceptance Criteria**
The following request can be executed with no problems:

```
curl -X POST "http://timetracker-api.azurewebsites.net/time-entries" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"project_id\": \"390d9d3a-ed2e-4d9a-bb28-2e633c1fbbb9\", \"start_date\": \"2020-04-17T00:50:37.201229\"}"
```

**Comment by EliuX** [comment]
This is probably what #86 is about. And regarding to the required fields:

- The activity_id was required in the [model graph](https://www.lucidchart.com/documents/edit/42736c71-b2dd-474b-9cba-dcf7c0559783/uR~JkchVdQXz?beaconFlowId=B8E1D76AAD71623C#?folder_id=home&browser=icon). But I can change that as it was required.
- JWT is not a requirement for the model, and that is part of the authentication mechanism which is not defined.

**Comment by EliuX** [comment]
![image](https://user-images.githubusercontent.com/6514740/79806335-c6c83d00-832d-11ea-9ae9-a6cdbb0e12d6.png)
I tested it and it worked.
