### ISSUE TITLE
Return current time-entry

### ISSUE THREAD

**Issue by enriquezrene** [ioet/time-tracker-backend#89]
As a user, I want to open the app and see the last time-entry created that has not been clocked-out so I can clock-out it whenever I want.

The endpoint will return a time-entry object using the information provided in the Authorization header (JWT). If not time-entry found a 404 needs to be returned. Bear in mind, the API only allows one active time-entry per user.

Once this endpoint has been implemented please provide all the details to the UI team.
Mention how this endpoint works as a comment in this ticket
https://github.com/ioet/time-tracker-ui/issues/150

**Comment by EliuX** [comment]
Ok, I have in mind an endpoint like
* GET https://timetracker-api.azurewebsites.net/time-entries/active
* GET https://timetracker-api.azurewebsites.net/time-entries/running
